# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

# Database
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

# Integration
integration.brapi.base-url=${BRAPI_BASE_URL}
integration.brapi.token=${BRAPI_TOKEN}
integration.coingecko.base-url=${COINGECKO_BASE_URL}
